# Generated by Django 5.1.7 on 2025-03-31 19:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_filme', models.CharField(max_length=50)),
                ('ano_de_lancamento', models.DateField()),
                ('estudio', models.CharField(max_length=50)),
                ('sinopse', models.TextField()),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.genero')),
            ],
        ),
    ]
