# Generated by Django 5.1.7 on 2025-03-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_genero_filme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuário',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m'),
        ),
    ]
